server:
  port: 9009

spring:
  application:
    name: huahua-sms

  rabbitmq:
    host: 10.2.21.36
    username: guest
    password: guest


api:
  send:
    appCode: 8ab263254de549e7ac71f4b6bd2db89d
