
spring:
  application:
    name: huahua-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/an_wenrui/huahua-config.git

  rabbitmq:
    host: 10.2.21.36
    username: guest
    password: guest
server:
  port: 12000


management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
