server: 
  port: 9005
spring: 
  application:  
    name: huahua-gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.2.21.36:3306/huahua_gathering?useUnicode=true&characterEncoding=UTF8
    username: root
    password: itcast
  jpa: 
    database: MySQL
    show-sql: true
#redis
  redis:
    host: 10.2.21.36
    port: 6379

